export let movements = [
    "Back squat",
    "Barbell bent over row",
    "Bench press Clean",
    "Clean & Jerk Cluster",
    "Deadlift",
    "Dumbbell Clean & Jerk",
    "Dumbbell Deadlift",
    "Dumbbell front squat",
    "Dumbbell",
    "Hang squat clean",
    "Dumbbell Jerk",
    "Dumbbell power clean",
    "Dumbbell Push Press",
    "Dumbbell shoulder press",
    "Dumbbell Shoulder to overhead",
    "Dumbbell Squat Clean",
    "Dumbbell Sumo deadlift high pull",
    "Dumbbell Thruster",
    "Dumbbell Waiter walk",
    "Farmer carry",
    "Front squat",
    "Good morning",
    "Ground to Overhead",
    "Hang power clean",
    "Hang power snatch",
    "Hang squat clean",
    "Jerk",
    "Medicine ball clean",
    "One-arm Dumbbell Snatch",
    "Overhead squat",
    "Overhead walk",
    "Overhead walking lunges",
    "Overhead walking lunges (with dumbbells)",
    "Power clean",
    "Power snatch",
    "Push Press Shoulder press",
    "Shoulder to overhead",
    "Snatch Snatch balance",
    "Sots press",
    "Sumo deadlift high pull",
    "Thruster",
    "Two-hand dumbbell Bent over row",
    "Zercher squat",
    "Barbell Turkish Get-up",
    "Dumbbell Swing",
    "Dumbbell Turkish Get-up",
    "Goblet squat",
    "Kettlebell snatch",
    "Kettlebell swing",
    "One-arm kettlebell swing",
    "Turkish Get-up",
    "Swimming",
    "Rowing",
    "Running",
    "Air Squat",
    "Assisted Pull-up",
    "Back extension",
    "Bar Muscle up",
    "Box jump",
    "Broad jump",
    "Burpee",
    "Burpee Pull-up",
    "Chest-to-bar pull-up",
    "Deficit push-up",
    "GHD sit-up",
    "GHD Wall ball",
    "Handstand",
    "Handstand push-up",
    "Hanging hip touches",
    "Hanging ring extension",
    "Hip extension",
    "Hip-Back extension",
    "Inverted Burpee",
    "Jumping jack",
    "Jumping Pull-up",
    "Knees to elbows",
    "Ladies’ push-up",
    "L-pull-up",
    "Lunge Lying leg raises",
    "Muscle up",
    "Pistol Pistol progression",
    "Plank",
    "Pull-up Push-up",
    "Ring dip",
    "Ring L-sit",
    "Ring pull-up",
    "Ring row",
    "Ring Tuck hold",
    "Rope climb",
    "Sit-up",
    "Sit-up Wall ball",
    "Stair step ascent",
    "Stair step descent",
    "Static bar L-sit",
    "Static bar Tuck hold",
    "Static Dip",
    "Static hang",
    "Strict pull-up",
    "Strict Ring pull-up",
    "Superman",
    "Toes-to-bar",
    "Toes-to-rings",
    "Tuck jump",
    "Walking Lunge",
    "Wall climb",
];